// Generated by @rvst/api — do not edit
import { query, mutation } from '@rvst/api/runtime';

export const getTodos = (params) => query('getTodos', params);
export const addTodo = (params) => mutation('addTodo', params);
export const toggleTodo = (params) => mutation('toggleTodo', params);
