export function generateClient(schema) {
  let code = '// Generated by @rvst/api — do not edit\n';
  code += "import { query, mutation } from '@rvst/api/runtime';\n\n";

  for (const cmd of schema.commands) {
    const fn = cmd.name.startsWith('get') || cmd.name.startsWith('list') || cmd.name.startsWith('find')
      ? 'query' : 'mutation';
    const nativeArg = cmd.native ? ', { native: true }' : '';
    code += `export const ${cmd.name} = (params) => ${fn}('${cmd.name}', params${nativeArg});\n`;
  }

  return code;
}
