/**
 * Map TypeScript types to Rust types.
 * @param {string} tsType
 * @returns {string}
 */
function mapType(tsType) {
  switch (tsType) {
    case 'number':
      return 'f64';
    case 'string':
      return 'String';
    case 'boolean':
      return 'bool';
    case 'Uint8Array':
      return 'Vec<u8>';
    default:
      return tsType;
  }
}

/**
 * Map a full type string (possibly array/optional) to a Rust type.
 * @param {string} typeStr - e.g. "User[]", "string", "number"
 * @returns {string}
 */
function mapFullType(typeStr) {
  const trimmed = typeStr.trim();
  if (trimmed.endsWith('[]')) {
    const inner = trimmed.slice(0, -2);
    return `Vec<${mapType(inner)}>`;
  }
  return mapType(trimmed);
}

/**
 * Convert a field to its Rust type string (handling repeated/optional).
 * @param {import('../types.js').Field} field
 * @returns {string}
 */
function fieldRustType(field) {
  let rustType = mapType(field.type);
  if (field.repeated) {
    rustType = `Vec<${rustType}>`;
  }
  if (field.optional) {
    rustType = `Option<${rustType}>`;
  }
  return rustType;
}

/**
 * Capitalize the first letter.
 * @param {string} s
 * @returns {string}
 */
function capitalize(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/**
 * Convert camelCase to snake_case.
 * @param {string} s
 * @returns {string}
 */
function toSnakeCase(s) {
  return s.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
}

/**
 * Parse an inline object type string like "{ limit: number; name: string }"
 * into an array of fields.
 * @param {string} raw
 * @returns {import('../types.js').Field[]}
 */
function parseInlineFields(raw) {
  const inner = raw.replace(/^\{/, '').replace(/\}$/, '').trim();
  if (!inner) return [];

  const parts = inner.split(/[;,]/).map((s) => s.trim()).filter(Boolean);
  return parts.map((part) => {
    const match = part.match(/^(\w+)(\?)?:\s*(.+)$/);
    if (!match) return null;
    const [, name, opt, typeStr] = match;
    const optional = !!opt;
    const trimmed = typeStr.trim();
    const repeated = trimmed.endsWith('[]');
    const type = repeated ? trimmed.slice(0, -2) : trimmed;
    return { name, type, repeated, optional };
  }).filter(Boolean);
}

/**
 * Render a Rust struct with serde derives.
 * @param {string} name
 * @param {import('../types.js').Field[]} fields
 * @returns {string}
 */
function renderStruct(name, fields) {
  const lines = [];
  lines.push('#[derive(Debug, Clone, Serialize, Deserialize)]');
  lines.push(`pub struct ${name} {`);
  for (const f of fields) {
    lines.push(`    pub ${f.name}: ${fieldRustType(f)},`);
  }
  lines.push('}');
  return lines.join('\n');
}

/**
 * Derive a handler trait name from a filename.
 * "users.svelte.ts" → "UsersHandler"
 * @param {string} filename
 * @returns {string}
 */
function traitNameFromFile(filename) {
  const base = filename.replace(/\.svelte\.ts$/, '').replace(/\.ts$/, '');
  const name = base.split('/').pop() || base;
  return capitalize(name) + 'Handler';
}

/**
 * Generate a Rust source file string from an ApiSchema.
 * Produces serde structs, a handler trait, and a register_handlers function.
 * @param {import('../types.js').ApiSchema} schema
 * @returns {string}
 */
export function generateRust(schema) {
  const blocks = [];
  const baseName = schema.file.replace(/\.svelte\.ts$/, '').replace(/\.ts$/, '');
  const shortName = baseName.split('/').pop() || baseName;

  blocks.push(`// ${shortName}.gen.rs — generated by @rvst/api, do not edit`);
  blocks.push('');
  blocks.push('use serde::{Deserialize, Serialize};');

  const knownMessages = new Set(schema.messages.map((m) => m.name));

  // Render interface-derived structs
  for (const msg of schema.messages) {
    blocks.push('');
    blocks.push(renderStruct(msg.name, msg.fields));
  }

  // Generate request structs for commands with inline types
  /** @type {{ cmd: import('../types.js').CommandDef, reqStructName: string }[]} */
  const commandEntries = [];

  for (const cmd of schema.commands) {
    const reqStructName = capitalize(cmd.name) + 'Request';
    const reqType = cmd.requestType.trim();

    if (reqType.startsWith('{')) {
      const fields = parseInlineFields(reqType);
      blocks.push('');
      blocks.push(renderStruct(reqStructName, fields));
    } else if (!knownMessages.has(reqType)) {
      // Primitive or unknown type — wrap it
      blocks.push('');
      blocks.push(renderStruct(reqStructName, [{ name: 'value', type: reqType, repeated: false, optional: false }]));
    }
    // If reqType is a known message name, we still create a request struct alias
    // Actually for known messages, generate a wrapper struct
    else {
      blocks.push('');
      blocks.push(renderStruct(reqStructName, [{ name: 'payload', type: reqType, repeated: false, optional: false }]));
    }

    commandEntries.push({ cmd, reqStructName });
  }

  // Handler trait
  if (commandEntries.length > 0) {
    const traitName = traitNameFromFile(schema.file);
    blocks.push('');

    const traitLines = [];
    traitLines.push(`pub trait ${traitName}: Send + Sync + 'static {`);

    for (const { cmd, reqStructName } of commandEntries) {
      const methodName = toSnakeCase(cmd.name);
      const returnType = mapFullType(cmd.responseType);
      const reqType = cmd.requestType.trim();

      // Determine the actual request type for the method signature
      let methodReqType = reqStructName;
      if (reqType.startsWith('{') || !knownMessages.has(reqType)) {
        methodReqType = reqStructName;
      } else {
        methodReqType = reqStructName;
      }

      traitLines.push(`    fn ${methodName}(&self, req: ${methodReqType}) -> ${returnType};`);
    }

    traitLines.push('}');
    blocks.push(traitLines.join('\n'));

    // register_handlers function
    blocks.push('');
    const regLines = [];
    regLines.push(`pub fn register_handlers<H: ${traitName}>(handler: std::sync::Arc<H>) {`);

    for (const { cmd, reqStructName } of commandEntries) {
      const methodName = toSnakeCase(cmd.name);

      regLines.push(`    let h = handler.clone();`);
      regLines.push(`    rvst_quickjs::register_command("${cmd.name}", Box::new(move |payload| {`);
      regLines.push(`        let req: ${reqStructName} = serde_json::from_str(payload).unwrap();`);
      regLines.push(`        let res = h.${methodName}(req);`);
      regLines.push(`        serde_json::to_string(&res).unwrap()`);
      regLines.push(`    }));`);
      regLines.push('');
    }

    // Remove trailing empty line
    if (regLines[regLines.length - 1] === '') {
      regLines.pop();
    }

    regLines.push('}');
    blocks.push(regLines.join('\n'));
  }

  return blocks.join('\n') + '\n';
}
