import { describe, it } from 'node:test';
import assert from 'node:assert';
import {
  extractRustFunctions,
  extractRustStructs,
  generateTsDeclarations,
  rustTypeToTs,
  splitGenericArgs,
} from './ts_from_rust.js';

const testRust = `
#[rvst::command]
pub fn process_image(path: String, quality: u32) -> ProcessResult {
    // ...
}

#[rvst::state]
pub struct ProcessResult {
    pub width: u32,
    pub height: u32,
    pub thumbnail_b64: String,
}

#[rvst::watch]
pub fn file_watcher(opts: WatchOpts, emit: impl Fn(Vec<FileChange>)) {
    // ...
}
`;

describe('splitGenericArgs', () => {
  it('splits simple args', () => {
    assert.deepStrictEqual(splitGenericArgs('String, u32'), ['String', 'u32']);
  });

  it('respects nested angle brackets', () => {
    assert.deepStrictEqual(
      splitGenericArgs('Vec<String>, HashMap<String, u32>'),
      ['Vec<String>', 'HashMap<String, u32>'],
    );
  });
});

describe('rustTypeToTs', () => {
  it('maps primitives', () => {
    assert.strictEqual(rustTypeToTs('String'), 'string');
    assert.strictEqual(rustTypeToTs('u32'), 'number');
    assert.strictEqual(rustTypeToTs('bool'), 'boolean');
    assert.strictEqual(rustTypeToTs('()'), 'void');
  });

  it('maps Vec<String> → string[]', () => {
    assert.strictEqual(rustTypeToTs('Vec<String>'), 'string[]');
  });

  it('maps Vec<u8> → Uint8Array', () => {
    assert.strictEqual(rustTypeToTs('Vec<u8>'), 'Uint8Array');
  });

  it('maps Option<u32> → number | null', () => {
    assert.strictEqual(rustTypeToTs('Option<u32>'), 'number | null');
  });

  it('maps HashMap<String, Vec<u32>> → Record<string, number[]>', () => {
    assert.strictEqual(
      rustTypeToTs('HashMap<String, Vec<u32>>'),
      'Record<string, number[]>',
    );
  });

  it('maps Result<T, E> → T', () => {
    assert.strictEqual(rustTypeToTs('Result<String, Error>'), 'string');
  });

  it('passes through custom struct names', () => {
    assert.strictEqual(rustTypeToTs('ProcessResult'), 'ProcessResult');
  });
});

describe('extractRustFunctions', () => {
  it('extracts command and watch functions', () => {
    const fns = extractRustFunctions(testRust);
    assert.strictEqual(fns.length, 2);
  });

  it('extracts command with correct params', () => {
    const fns = extractRustFunctions(testRust);
    const cmd = fns.find((f) => f.name === 'process_image');
    assert.ok(cmd);
    assert.strictEqual(cmd.annotation, 'command');
    assert.deepStrictEqual(cmd.params, [
      { name: 'path', type: 'String' },
      { name: 'quality', type: 'u32' },
    ]);
    assert.strictEqual(cmd.returnType, 'ProcessResult');
  });

  it('extracts watch function and skips impl Fn params', () => {
    const fns = extractRustFunctions(testRust);
    const watch = fns.find((f) => f.name === 'file_watcher');
    assert.ok(watch);
    assert.strictEqual(watch.annotation, 'watch');
    assert.strictEqual(watch.params.length, 1);
    assert.strictEqual(watch.params[0].name, 'opts');
    assert.strictEqual(watch.params[0].type, 'WatchOpts');
  });

  it('handles async fn', () => {
    const src = `
#[rvst::command]
pub async fn fetch_data(url: String) -> Vec<u8> {
    // ...
}
`;
    const fns = extractRustFunctions(src);
    assert.strictEqual(fns.length, 1);
    assert.strictEqual(fns[0].name, 'fetch_data');
    assert.strictEqual(fns[0].returnType, 'Vec<u8>');
  });
});

describe('extractRustStructs', () => {
  it('extracts rvst::state struct', () => {
    const structs = extractRustStructs(testRust);
    assert.strictEqual(structs.length, 1);
    assert.strictEqual(structs[0].name, 'ProcessResult');
    assert.strictEqual(structs[0].fields.length, 3);
  });

  it('parses field types correctly', () => {
    const structs = extractRustStructs(testRust);
    const pr = structs[0];
    assert.strictEqual(pr.fields[0].name, 'width');
    assert.strictEqual(pr.fields[0].type, 'u32');
    assert.strictEqual(pr.fields[2].name, 'thumbnail_b64');
    assert.strictEqual(pr.fields[2].type, 'String');
  });

  it('handles optional fields', () => {
    const src = `
#[derive(Serialize, Deserialize)]
pub struct Config {
    pub name: String,
    pub debug: Option<bool>,
}
`;
    const structs = extractRustStructs(src);
    assert.strictEqual(structs.length, 1);
    const debug = structs[0].fields.find((f) => f.name === 'debug');
    assert.ok(debug);
    assert.strictEqual(debug.optional, true);
    assert.strictEqual(debug.type, 'bool');
  });
});

describe('generateTsDeclarations', () => {
  it('generates valid .d.ts content', () => {
    const dts = generateTsDeclarations(testRust);
    assert.ok(dts.includes('Auto-generated by rvst-codegen'));
    assert.ok(dts.includes('export interface ProcessResult'));
    assert.ok(dts.includes('width: number'));
    assert.ok(dts.includes('height: number'));
    assert.ok(dts.includes('thumbnailB64: string'));
    assert.ok(dts.includes('declare namespace rvst'));
    assert.ok(dts.includes('function processImage(path: string, quality: number): Promise<ProcessResult>'));
    assert.ok(dts.includes('function fileWatcher(opts: WatchOpts): AsyncIterable'));
  });

  it('produces no namespace block when no functions', () => {
    const src = `
#[rvst::state]
pub struct Foo {
    pub x: f64,
}
`;
    const dts = generateTsDeclarations(src);
    assert.ok(dts.includes('export interface Foo'));
    assert.ok(!dts.includes('declare namespace'));
  });
});
